import type { Metadata } from "next";
import "./globals.css";
import React from "react";
import { Geist, Wittgenstein } from "next/font/google";
import Header from "./components/Header";
import Footer from "@/app/components/Footer";
import TopBar from "./components/TopBar";
import Nav from "./components/nav";

// Google Fonts setup
const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const wittgenstein = Wittgenstein({
    variable: "--font-wittgenstein",
    subsets: ["latin"],
    weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${wittgenstein.variable} antialiased`}
      >
        <TopBar />
        <Header />
        {/* <Nav /> */}
        {children}
        <Footer />
      </body>
    </html>
  );
}
